let data = {"states": {
    "aguascalientes":{
            "Democracia":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Federalismo":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SeguridadNan":{
                "hombres":0,
                "mujeres":0,
                "total":0
            }, 
            "Militarizacion":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SeguridadPu":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SistemadeJusticia":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Derechos":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "CombateCorrupcion":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "DesigualdadDis":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Salud":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SeguridadSocial":{
                "hombres":0,
                "mujeres":0,
                "total":0
            }, 
            "Educacion":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "CulturaDeporte":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "CienciaTecnologia":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "EconomiaAcceso":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Empleo":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "DesarrolloSustentable":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Energia":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Mineria":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SectorAgroalimentario":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "SectorTuristico":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "DesarrolloRegional":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "PresenciaGlobal":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "LibreComercio":{
                "hombres":0,
                "mujeres":0,
                "total":0
            },
            "Migración":{
                "hombres":0,
                "mujeres":0,
                "total":0
            }
        
    },
    "campeche":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },
    "chihuahua":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },
    
    "sinaloa":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "ciudaddemex":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "nuevoleon":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "colima":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "yucatan":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "quintanaro":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    }, 

    "guerrero":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "bajacalifornia":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "bajacalsur":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "chiapas":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "durango":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "coahuila":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },
    
    "guanajuato":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "hidalgo":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "jalisco":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "edomex":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "michoacan":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "morelos":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "nayarit":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "oaxaca":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "puebla":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "queretaro":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "sanluispotosi":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "sonora":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "tabasco":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "tamaulipas":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "tlaxcala":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "veracruz":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    },

    "zacatecas":{
        "Democracia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Federalismo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadNan":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Militarizacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadPu":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SistemadeJusticia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Derechos":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CombateCorrupcion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesigualdadDis":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Salud":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SeguridadSocial":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }, 
        "Educacion":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CulturaDeporte":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "CienciaTecnologia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "EconomiaAcceso":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Empleo":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloSustentable":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Energia":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Mineria":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorAgroalimentario":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "SectorTuristico":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "DesarrolloRegional":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "PresenciaGlobal":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "LibreComercio":{
            "hombres":0,
            "mujeres":0,
            "total":0
        },
        "Migración":{
            "hombres":0,
            "mujeres":0,
            "total":0
        }
    }

}} 

module.exports.data = data 